name: backgroundtask_example
description: Demonstrates how to use the backgroundtask plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mailer: ^3.0.4
  android_alarm_manager: ^0.4.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter

  backgroundtask:
    path: ../
flutter:
  uses-material-design: true
