name: backgroundtask
description: description
version: 0.0.1
author:
homepage: lince.com.br

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.lince.backgroundtask
    pluginClass: BackgroundtaskPlugin